/* Generated by bin2c, do not edit manually */
#ifndef __attention_h_included
#define __attention_h_included

/* Contents of file attention.raw */
extern const long int attention_raw_size;
extern const unsigned char attention_raw[9536];

#endif    /* __attention_h_included */
